### ISSUE TITLE
"Freezes" in docker when taking screenshot 

### ISSUE THREAD

**Issue by jarmo-fi** [ZFC-Digital/puppeteer-real-browser#181]
### Description

Running puppeteer-real-browser inside docker. Docker image is based on Ubuntu 22.04

Code freezes for 30 or so seconds when taking screenshot and then fails with protocol timeout error. The same error can also happen while scrolling down when the page is long and contains a lot of images.

After a lot of digging in I finally found out that this is caused by different behaviour of /dev/shm usage in puppeteer vs puppeteer-real-browser.

I solved this by adding --disable-dev-shm-usage flag to chrome launching.
```
	const { browser, page } = await connect({
		headless: true, turnstile: true, disableXvfb: false,
		ignoreAllFlags: false, customConfig: {
			chromeFlags: [
				'--no-first-run',
				'--disable-dev-shm-usage'
			]
		}
	});
```

The alternative solution is to allocate more shm in container start, but I guess using --disable-dev-shm-usage is better option. Or is shm needed to hide that we are a bot?

The same problem does not happen in std puppeteer as it uses --disable-dev-shm-usage flag by default when launching chrome.

Not sure if this is a bug or just a fyi for others.... but anyway, it would be nice to know which one is better solution

### Full steps to reproduce the issue

Change any of the tests https://github.com/zfcsoftware/puppeteer-real-browser/blob/main/test/esm/test.js to download some real page which have at least dozen  images

Scroll to the bottom in steps to get the lazy images to download:
```
	let height = 12000;
	let scroll = 0;
	while (scroll < height) {
		const scrollHeight = getRandomInt(10, 1200);
		await page.mouse.wheel({ deltaY: scrollHeight });
		scroll += scrollHeight;
		await Utils.delay(getRandomInt(50, 400));
	}
```

and then take screenshot
`      const shot = await page.screenshot({ type: 'jpeg', fullPage: true });`

=> throws Protocol timeout error while the real reason is "out of shm"

### Issue Type

Bug

### Operating System

Linux

### Do you use Docker?

Docker

**Comment by mdervisaygan** [comment]
Thank you
