### ISSUE TITLE
Browser doesn't display on Ubuntu 22.04 & 20.04.4 LTS

### ISSUE THREAD

**Issue by rainb3rry** [ZFC-Digital/puppeteer-real-browser#184]
### Description

Same code working on OS X but it doesn't display the browser on Ubuntu 20.04.4 LTS

### Full steps to reproduce the issue

Code,
```

const { connect } = require("puppeteer-real-browser")

async function test() {

    const { browser, page } = await connect({

        headless: false,
        

        args: [
          '--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.5249.119 Safari/537.36'
        ],

        // customConfig: {
        //   userDataDir: `/root/.config/google-chrome/profile_prod`,
        //   chromePath: `/usr/bin/google-chrome`
        // },

        turnstile: false,

        connectOption: {},

        disableXvfb: true,
        ignoreAllFlags: false
        // proxy:{
        //     host:'<proxy-host>',
        //     port:'<proxy-port>',
        //     username:'<proxy-username>',
        //     password:'<proxy-password>'
        // }

    })
  //   await page.setViewport({
  //     width: 1920,
  //     height: 1080
  // });
    await page.goto('https://google.com')

}

test()
```
It's running but browser doesn't display at the server RDP.

Also tried with `turnstile: true` and `disableXvfb: false` but the result was same.

https://github.com/user-attachments/assets/5635ab62-a54a-49ec-82b0-29b5e15e26e0

### Issue Type

Bug

### Operating System

Other

### Do you use Docker?

I don't use Docker

**Comment by zfcsoftware** [comment]
The library currently only supports ubuntu and windows operating systems. I can't help you with this, but you can investigate how the browser can appear with puppeteer on the operating system you are using.

**Comment by RubberArchind** [comment]
> The library currently only supports ubuntu and windows operating systems. I can't help you with this, but you can investigate how the browser can appear with puppeteer on the operating system you are using.

Well isn't he say the problem was on Ubuntu? the code works on OS X but not working when he tried on Ubuntu 20.04.4 LTS

**Comment by rainb3rry** [comment]
> > The library currently only supports ubuntu and windows operating systems. I can't help you with this, but you can investigate how the browser can appear with puppeteer on the operating system you are using.
> 
> Well isn't he say the problem was on Ubuntu? the code works on OS X but not working when he tried on Ubuntu 20.04.4 LTS

Also not working on `Ubuntu 22.04 (LTS) x64` from DigitalOcean, I think his projects only works on his local LoL

**Comment by zfcsoftware** [comment]
> > > The library currently only supports ubuntu and windows operating systems. I can't help you with this, but you can investigate how the browser can appear with puppeteer on the operating system you are using.
> > 
> > 
> > Well isn't he say the problem was on Ubuntu? the code works on OS X but not working when he tried on Ubuntu 20.04.4 LTS
> 
> Also not working on `Ubuntu 22.04 (LTS) x64` from DigitalOcean, I think his project only works on his local LoL
> 
> <img alt="Screenshot 2024-10-07 at 8 53 40 AM" width="1728" src="https://private-user-images.githubusercontent.com/26173028/373999574-194e9eb2-a1d6-424e-bdc9-d7162fa82d23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyOTAzMDMsIm5iZiI6MTcyODI5MDAwMywicGF0aCI6Ii8yNjE3MzAyOC8zNzM5OTk1NzQtMTk0ZTllYjItYTFkNi00MjRlLWJkYzktZDcxNjJmYTgyZDIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDA4MzMyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiNzAwNGE1Njc2OTMyMzUzZTAyYmU0ZmFhZTNiN2U5ZDI5YjdhNDkwZDhjMTI3MGQwMWE5ZTNkMmE2N2Q1MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nTX3sDQyDvE_uxnnf-u_3_jae4DxlSngBvtE6zy1OS8">


The project works seamlessly in ubuntu, macos, windows environments. 
https://github.com/zfcsoftware/cf-clearance-scraper/actions
As you can see in a different project created using this project, it works fine.
I think you have somehow added an interface to a linux that can only be accessed from the console (https://phoenixnap.com/kb/how-to-install-a-gui-on-ubuntu) This is probably why it is not working. You have to have a real screen to see the browser. Otherwise you have to work with xvfb in a virtual graphical interface.
This library has been tested on many providers such as Google Cloud Run, Heroku, Contabo, Netcup, Vultr and many others and no problems were encountered.
People like you, who are disrespectful and mock open source developers, please stay away from my projects. Stop making fun of others for your own lack of knowledge. I am blocking you.
