### ISSUE TITLE
browser ınfo bar not close

### ISSUE THREAD

**Issue by 6ix9s** [ZFC-Digital/puppeteer-real-browser#200]
args: 
            [
	        '--disable-setuid-sandbox', 
		'--disable-notifications',  
            '--no-sandbox',
            '--disable-web-security',
		'--incognito',
		'--disable-infobars',
                `--start-maximized`,
                '--disable-features=IsolateOrigins,site-per-process',
                '--allow-running-insecure-content',
                '--disable-dev-shm-usage',
                '--disable-gpu',
                '--ash-no-nudges',
                '--disable-save-password-bubble'
            ]
            
            
          //The arguments I used are above, but no matter what I did, I could not close the browser information bar.

**Comment by RubberArchind** [comment]
you can try to  set  `ignoreAllFlags: true` to make those flags worked

**Comment by RubberArchind** [comment]
pretty weird im run the same thing and its worked when i set it to true, where you run it, windows, mac or linux?

**Comment by 6ix9s** [comment]
> pretty weird im run the same thing and its worked when i set it to true, where you run it, windows, mac or linux?

i used windows 

puppeteer-real-browser: 1.3.12
The version I use

**Comment by mdervisaygan** [comment]
Having that bar doesn't make much difference. If you still want to turn it off, you can turn off the no-sandbox flag with ignoreAllFlags.
