### ISSUE TITLE
 Recaptcha V3

### ISSUE THREAD

**Issue by codsec** [ZFC-Digital/puppeteer-real-browser#201]
### Description

it not a issue tbh, i just wanna know, how exacly i can make a "bypass" for the recaptchav3? i tried everything and could make it work, if someone has a example that would be great for me.

### Full steps to reproduce the issue

(not a issue just a question)

### Issue Type

Support

### Operating System

Windows 10

### Do you use Docker?

I don't use Docker

**Comment by RubberArchind** [comment]
you better move this to the discussion section, it will fit better there

**Comment by codsec** [comment]
> you better move this to the discussion section, it will fit better there

Sorry

**Comment by RubberArchind** [comment]
there was already a discussion about Recaptcha V3 anyway #187

**Comment by mdervisaygan** [comment]
https://github.com/ZFC-Digital/puppeteer-real-browser?tab=readme-ov-file#why-cant-i-pass-recaptcha-v3
