### ISSUE TITLE
persistent context puppeteer

### ISSUE THREAD

**Issue by aealduraiweesh** [ZFC-Digital/puppeteer-real-browser#204]
# Hello , I am trying get persistent context but its not working out. Is it unsupported currently or am i missing something?

Things I have tried:
I tried writing in the path directly 
    //   userDataDir: 'C:\\Users\\USERNAME\\Desktop\\WorkSpace\\Learning\\NODE\\Puppter-Real-Browser\\mycontext',

I tried running it via powershell.

The file is always empty after running 
....
```
const path = require('path');
const userDataDirPath = path.resolve(__dirname, 'puppeteer_data');
```
....

```
async function test() {
  let browser, page;
  try {
    // Connect to the browser
    const connected = await connect({
      headless: true,
      userDataDir: userDataDirPath, // Shorter path for testing

      // Add other options if needed
    });
```
Issue Type
Bug

Operating System
Windows

Do you use Docker?
No

**Comment by mdervisaygan** [comment]
in customConfig:
https://github.com/ZFC-Digital/puppeteer-real-browser?tab=readme-ov-file#usage
