### ISSUE TITLE
error getting landing page html when there are many redirects

### ISSUE THREAD

**Issue by Quochung1st-dev** [ZFC-Digital/puppeteer-real-browser#212]
### Description

const { browser, page } = await connect({

        headless: false,

        args: [],

        customConfig: {},

        turnstile: true,

        connectOption: {},

        disableXvfb: false,
        ignoreAllFlags: false
        // proxy:{
        //     host:'<proxy-host>',
        //     port:'<proxy-port>',
        //     username:'<proxy-username>',
        //     password:'<proxy-password>'
        // }

    })
    await page.goto('https://lazytruyen.com')
    const html = await page.content()
    console.log(html)
    
![Screenshot_8](https://github.com/user-attachments/assets/f57e83d8-f54f-4f82-ba06-20b0db5776a9)

### Full steps to reproduce the issue

.

### Issue Type

Support

### Operating System

Other

### Do you use Docker?

I don't use Docker

**Comment by mdervisaygan** [comment]
Please try:
https://stackoverflow.com/a/57677369
