### ISSUE TITLE
puppeteer-real-browser displays webpages incorrectly (frame issue)

### ISSUE THREAD

**Issue by aguyinmontreal** [ZFC-Digital/puppeteer-real-browser#216]
### Description

When loading the following webpage, the scroll bar doesn't show and it is impossible to scroll to the last line (the line with the four zeros [`0000`]) even with the mouse (scroll wheel). This webpage works fine with normal puppeteer and normal Chrome, so the issue must be with puppeteer-real-browser.

**My conditions:**
- Headless: false
- On Windows
- Screen resolution 1366x768 and 100% scale
- 100% zoom on webpage (no zoom)
- Browser window is maximized
```
connectOption: {
			defaultViewport: {
				width: 1366,
				height: 768,
				deviceScaleFactor: 1,
			},
		},
```

### Full steps to reproduce the issue

use `page.setContent()` with the following HTML code I prepared for debugging:

[scroll_example.zip](https://github.com/user-attachments/files/17653431/scroll_example.zip)

### Issue Type

Bug

### Operating System

Windows

### Do you use Docker?

No

**Comment by mdervisaygan** [comment]
It should be fixed with the last update. If not, can you provide information on this issue? Thank you.
