### ISSUE TITLE
It is not possible to click on the WAF of cloudflare Pro or business plan

### ISSUE THREAD

**Issue by Gaimoydev** [ZFC-Digital/puppeteer-real-browser#218]
### Description

It is not possible to click on the WAF of cloudflare Pro or business plan
I want to know how to click
https://bakamarisa.shop/
https://91av.live/ cf pro

### Full steps to reproduce the issue

      let verify = null
      let startDate = Date.now()
      while (!verify && (Date.now() - startDate) < 30000) {
          verify = await page.evaluate(() => { return document.querySelector('.link_row') ? true : null }).catch(() => null)
          await new Promise(r => setTimeout(r, 1000));
      }

### Issue Type

Support

### Operating System

Linux

### Do you use Docker?

I don't use Docker

**Comment by RubberArchind** [comment]
have you set turnstile to true?

**Comment by Gaimoydev** [comment]
> have you set turnstile to true?您是否将 turnstile 设置为 true？

  const options = {
    headless: false,
    ignoreHTTPSErrors: true,
    turnstile: true,
    args: [
      "--proxy-server=http://" + browserProxy,
      "--no-sandbox",
      "--no-first-run",
      "--ignore-certificate-errors",
      "--disable-extensions",
      "--test-type",
      "--user-agent=" + randomUA,
      "--disable-gpu"
    ],
    customConfig: {},
    connectOption: {
      defaultViewport: null  // 禁用默认的视口设置
    },
    plugins: [
      require('puppeteer-extra-plugin-click-and-wait')()
    ]
  };

**Comment by mdervisaygan** [comment]
This library successfully passes Cloudflare enterprise and free plan protections. The args values you add may reduce the reliability of the library. I added a test video below, you can try it with the test code. There does not seem to be a problem.

```
const { connect } = require("puppeteer-real-browser")

async function test() {

    const { browser, page } = await connect({
        turnstile: true,
        proxy: proxy,
        disableXvfb: true
    })
    await page.goto('https://91av.live/')

}

test()
```

https://github.com/user-attachments/assets/848220be-2eb6-4aef-98fb-a3542591cb50

**Comment by Gaimoydev** [comment]
> This library successfully passes Cloudflare enterprise and free plan protections. The args values you add may reduce the reliability of the library. I added a test video below, you can try it with the test code. There does not seem to be a problem.该库成功通过了 Cloudflare 企业和免费计划保护。您添加的 args 值可能会降低库的可靠性。我在下面添加了一个测试视频，你可以用测试代码来试试。似乎没有问题。
> 
> ```
> const { connect } = require("puppeteer-real-browser")
> 
> async function test() {
> 
>     const { browser, page } = await connect({
>         turnstile: true,
>         proxy: proxy,
>         disableXvfb: true
>     })
>     await page.goto('https://91av.live/')
> 
> }
> 
> test()
> ```
> 
>  2024-11-09.12-09-41.mp4

No extra action is required, just add the “turnstile: true” option?

**Comment by mdervisaygan** [comment]
> > This library successfully passes Cloudflare enterprise and free plan protections. The args values you add may reduce the reliability of the library. I added a test video below, you can try it with the test code. There does not seem to be a problem.该库成功通过了 Cloudflare 企业和免费计划保护。您添加的 args 值可能会降低库的可靠性。我在下面添加了一个测试视频，你可以用测试代码来试试。似乎没有问题。
> > ```
> > const { connect } = require("puppeteer-real-browser")
> > 
> > async function test() {
> > 
> >     const { browser, page } = await connect({
> >         turnstile: true,
> >         proxy: proxy,
> >         disableXvfb: true
> >     })
> >     await page.goto('https://91av.live/')
> > 
> > }
> > 
> > test()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 2024-11-09.12-09-41.mp4
> 
> No extra action is required, just add the “turnstile: true” option?

Yes just add turnstile: true, which launches a secure browser when you add it. Any addition you make can cause you to be detected.

**Comment by Gaimoydev** [comment]
> > > This library successfully passes Cloudflare enterprise and free plan protections. The args values you add may reduce the reliability of the library. I added a test video below, you can try it with the test code. There does not seem to be a problem.该库成功通过了 Cloudflare 企业和免费计划保护。您添加的 args 值可能会降低库的可靠性。我在下面添加了一个测试视频，你可以用测试代码来试试。似乎没有问题。
> > > ```
> > > const { connect } = require("puppeteer-real-browser")
> > > 
> > > async function test() {
> > > 
> > >     const { browser, page } = await connect({
> > >         turnstile: true,
> > >         proxy: proxy,
> > >         disableXvfb: true
> > >     })
> > >     await page.goto('https://91av.live/')
> > > 
> > > }
> > > 
> > > test()
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 2024-11-09.12-09-41.mp4
> > 
> > 
> > No extra action is required, just add the “turnstile: true” option?无需额外操作，只需添加 “turnstile： true” 选项即可？
> 
> Yes just add turnstile: true, which launches a secure browser when you add it. Any addition you make can cause you to be detected.是的，只需添加 turnstile： true，它会在您添加时启动一个安全的浏览器。您所做的任何添加都可能导致您被检测到。

ok thx!

**Comment by Gaimoydev** [comment]
> > > This library successfully passes Cloudflare enterprise and free plan protections. The args values you add may reduce the reliability of the library. I added a test video below, you can try it with the test code. There does not seem to be a problem.该库成功通过了 Cloudflare 企业和免费计划保护。您添加的 args 值可能会降低库的可靠性。我在下面添加了一个测试视频，你可以用测试代码来试试。似乎没有问题。
> > > ```
> > > const { connect } = require("puppeteer-real-browser")
> > > 
> > > async function test() {
> > > 
> > >     const { browser, page } = await connect({
> > >         turnstile: true,
> > >         proxy: proxy,
> > >         disableXvfb: true
> > >     })
> > >     await page.goto('https://91av.live/')
> > > 
> > > }
> > > 
> > > test()
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 2024-11-09.12-09-41.mp4
> > 
> > 
> > No extra action is required, just add the “turnstile: true” option?无需额外操作，只需添加 “turnstile： true” 选项即可？
> 
> Yes just add turnstile: true, which launches a secure browser when you add it. Any addition you make can cause you to be detected.是的，只需添加 turnstile： true，它会在您添加时启动一个安全的浏览器。您所做的任何添加都可能导致您被检测到。

https://91av.live/ If it's a custom cloudflareWAF, can you click on it?

**Comment by mdervisaygan** [comment]
> > > > This library successfully passes Cloudflare enterprise and free plan protections. The args values you add may reduce the reliability of the library. I added a test video below, you can try it with the test code. There does not seem to be a problem.该库成功通过了 Cloudflare 企业和免费计划保护。您添加的 args 值可能会降低库的可靠性。我在下面添加了一个测试视频，你可以用测试代码来试试。似乎没有问题。
> > > > ```
> > > > const { connect } = require("puppeteer-real-browser")
> > > > 
> > > > async function test() {
> > > > 
> > > >     const { browser, page } = await connect({
> > > >         turnstile: true,
> > > >         proxy: proxy,
> > > >         disableXvfb: true
> > > >     })
> > > >     await page.goto('https://91av.live/')
> > > > 
> > > > }
> > > > 
> > > > test()
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 2024-11-09.12-09-41.mp4
> > > 
> > > 
> > > No extra action is required, just add the “turnstile: true” option?无需额外操作，只需添加 “turnstile： true” 选项即可？
> > 
> > 
> > Yes just add turnstile: true, which launches a secure browser when you add it. Any addition you make can cause you to be detected.是的，只需添加 turnstile： true，它会在您添加时启动一个安全的浏览器。您所做的任何添加都可能导致您被检测到。
> 
> https://91av.live/ If it's a custom cloudflareWAF, can click?

I think that site is only accessible from China. It blocks my ip addresses and proxies directly. But it has been tested many times on Openai corporate waf. It passed without any problem. Can you send a video if you could not pass with the sample code I gave?

**Comment by Gaimoydev** [comment]
> > > > > This library successfully passes Cloudflare enterprise and free plan protections. The args values you add may reduce the reliability of the library. I added a test video below, you can try it with the test code. There does not seem to be a problem.该库成功通过了 Cloudflare 企业和免费计划保护。您添加的 args 值可能会降低库的可靠性。我在下面添加了一个测试视频，你可以用测试代码来试试。似乎没有问题。
> > > > > ```
> > > > > const { connect } = require("puppeteer-real-browser")
> > > > > 
> > > > > async function test() {
> > > > > 
> > > > >     const { browser, page } = await connect({
> > > > >         turnstile: true,
> > > > >         proxy: proxy,
> > > > >         disableXvfb: true
> > > > >     })
> > > > >     await page.goto('https://91av.live/')
> > > > > 
> > > > > }
> > > > > 
> > > > > test()
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > 2024-11-09.12-09-41.mp4
> > > > 
> > > > 
> > > > No extra action is required, just add the “turnstile: true” option?无需额外操作，只需添加 “turnstile： true” 选项即可？无需额外操作，只需添加 “turnstile： true” 选项？无需额外操作，只需添加 “turnstile： true” 选项即可？
> > > 
> > > 
> > > Yes just add turnstile: true, which launches a secure browser when you add it. Any addition you make can cause you to be detected.是的，只需添加 turnstile： true，它会在您添加时启动一个安全的浏览器。您所做的任何添加都可能导致您被检测到。
> > 
> > 
> > https://91av.live/ If it's a custom cloudflareWAF, can click?https://91av.live/如果是自定义的 cloudflareWAF，可以点击吗？
> 
> I think that site is only accessible from China. It blocks my ip addresses and proxies directly. But it has been tested many times on Openai corporate waf. It passed without any problem. Can you send a video if you could not pass with the sample code I gave?我认为该网站只能从中国访问。它直接阻止我的 IP 地址和代理。但它已经在 Openai 企业 waf 上经过多次测试。它顺利通过了。如果您无法通过我提供的示例代码，您可以发送视频吗？

Problem solved, thx!
