### ISSUE TITLE
thanks for all 

### ISSUE THREAD

**Issue by barutlift** [ZFC-Digital/puppeteer-real-browser#221]
### Description

i dont have a problem i want to say that thanks for all this library is amazing what can i say i dont know only thanks for everything

### Full steps to reproduce the issue

not problem

### Do you use Docker?

None

**Comment by Zvih** [comment]
Totally agree, this library saves lives! :-)

**Comment by Skorchekd** [comment]
ive been having fingerprinting issues..

**Comment by barutlift** [comment]
> ive been having fingerprinting issues..

https://github.com/ZFC-Digital/puppeteer-real-browser/issues/205

**Comment by barutlift** [comment]
@Skorchekd 
maybe that works but i didnt use it. him was use with puppeteer maybe it works with puppeteer-real-browser. u can try it
https://github.com/ZFC-Digital/puppeteer-afp

**Comment by mdervisaygan** [comment]
Hello, thank you for this nice problem. It makes me very happy that my open source software solves other people's problems.
@nwebson is the person to thank. I would like to thank him for open sourcing the rebrowser project and making a great contribution to the node.js ecosystem.

**Comment by baba990aini** [comment]
this's a good lib

**Comment by 0-don** [comment]
the best
