### ISSUE TITLE
page.pause() 

### ISSUE THREAD

**Issue by ayberkdikcinar** [ZFC-Digital/puppeteer-real-browser#223]
is there any way to pause like page.pause() functionality to handle manual steps?

**Comment by RubberArchind** [comment]
I think You can use nodejs functionalities for this. Something like
 https://stackoverflow.com/questions/19687407/press-any-key-to-continue-in-nodejs#49959557

Or if the "manual step" result a spesific UI to be appeared, you can just wait for that element
