### ISSUE TITLE
detected on the website: https://fingerprint.com/products/bot-detection/

### ISSUE THREAD

**Issue by fernandobragasilva** [ZFC-Digital/puppeteer-real-browser#224]
### Description

Did I do something wrong? 

I'm using Chrome 130, windows 11

detected on the website:
https://fingerprint.com/products/bot-detection/

### Full steps to reproduce the issue

Here is the code used:

```
const { connect } = require('puppeteer-real-browser');
(async () => {
  var { browser, page } = await connect({
    headless: false,
    args: [],
    customConfig: {},
    turnstile: true,
    connectOption: {},
    disableXvfb: false,
    ignoreAllFlags: false
    // proxy:{
    //     host:'<proxy-host>',
    //     port:'<proxy-port>',
    //     username:'<proxy-username>',
    //     password:'<proxy-password>'
    // }
  })

  // Obtém a versão do navegador
  const browserVersion = await browser.version();
  console.log('Browser Version:', browserVersion);

  // const page = await browser.newPage();
  // [page] = await browser.pages();
  console.log("started...");
  page.waitForTimeout = async (milis) => await new Promise(resolve => setTimeout(resolve, milis));

  await page.goto("https://abrahamjuliot.github.io/creepjs/");
  await page.waitForTimeout(6000)
  await page.screenshot({ path: "abrahamjuliot.png", fullPage: true });

  await page.goto("https://iphey.com/");
  await page.waitForTimeout(10000)
  await page.screenshot({ path: "iphey.png", fullPage: true });

  await page.goto("https://pixelscan.net/");
  await page.waitForTimeout(10000)
  await page.screenshot({ path: "pixelscan.png", fullPage: true });

  await page.goto("https://fingerprintjs.github.io/BotD/");
  await page.waitForTimeout(5000)
  await page.screenshot({ path: "BotD.png", fullPage: true });

  await page.goto("https://fingerprint.com/products/bot-detection/");
  await page.waitForTimeout(5000)
  await page.screenshot({ path: "fingerprintjs.png", fullPage: true });

  await page.goto("https://arh.antoinevastel.com/bots/areyouheadless");
  await page.waitForTimeout(5000)
  await page.screenshot({ path: "areyouheadless.png", fullPage: true });

  await page.goto("https://www.browserscan.net/bot-detection");
  await page.waitForTimeout(5000)
  await page.screenshot({ path: "detect/browserscan.png", fullPage: true });

  await browser.close();
})();
```

### Issue Type

Performance

### Operating System

Other

### Do you use Docker?

I don't use Docker

**Comment by RubberArchind** [comment]
I am not detected as a robot in that website, but im using Browser Version: Chrome/131.0.6778.69, im in windows 11 too

**Comment by fernandobragasilva** [comment]
> I am not detected as a robot in that website, but im using Browser Version: Chrome/131.0.6778.69, im in windows 11 too

Could you tell me the settings you currently use?
puppeteer version?,
Node Version?
Chrome for testing or using real chrome on the machine?

**Comment by aguyinmontreal** [comment]
@fernandobragasilva do you have the last version of puppeteer-real-browser installed? Looks similar to #145

**Comment by RubberArchind** [comment]
> > I am not detected as a robot in that website, but im using Browser Version: Chrome/131.0.6778.69, im in windows 11 too
> 
> Could you tell me the settings you currently use? puppeteer version?, Node Version? Chrome for testing or using real chrome on the machine?

I use the same setting like yours,
I use the latest version of this lib,
node version 20.15
yes im using real chrome on the machine...

**Comment by fernandobragasilva** [comment]
It's resolved, I'm sorry, it was outdated,
I would like it to work with headless:'new', I got it in version Chrome/116.0.5845.188

versions above I am detected, is there a way to make headless: 'new' work on more current chrome versions?

**Comment by RubberArchind** [comment]
why you want to use 'new' mode? it will make the browser more like a bot rather than real one

**Comment by fernandobragasilva** [comment]
> why you want to use 'new' mode? it will make the browser more like a bot rather than real one

performance, lower memory consumption, or does it not make sense as before?

**Comment by RubberArchind** [comment]
The new mode doesn't really made to have better performance

https://github.com/puppeteer/puppeteer/issues/12982#issuecomment-2297998943

And if you care about the resource usage it's highly suggested to use docker for this as you can just set the maximum resource it used, you can play with it and find the optimal settings.

**Comment by fernandobragasilva** [comment]
Thank you everyone for the clarifications
