### ISSUE TITLE
Can you provide a detailed document？

### ISSUE THREAD

**Issue by baba990aini** [ZFC-Digital/puppeteer-real-browser#227]
### Description

I am not very clear about the available options for APIs and configuration items

### Full steps to reproduce the issue

I want to set the value of a parameter, but I'm not sure what allowed content is

### Issue Type

Documentation Request

### Operating System

Mac OS

### Do you use Docker?

None

**Comment by RubberArchind** [comment]
Thats where typescripts come to help, your IDE should be cleaver enough to show you what options available to use.
