### ISSUE TITLE
save user data faill

### ISSUE THREAD

**Issue by baba990aini** [ZFC-Digital/puppeteer-real-browser#228]
### Description

      customConfig: {
        userDataDir: path.resolve(process.cwd(),'user_data')
      }
Unable to start after configuration

### Full steps to reproduce the issue

`
    const { browser, page } = await connect({
      headless: false,
      args: [],
      customConfig: {
        userDataDir: path.resolve(process.cwd(),'user_data')
      },
      turnstile: true,
      connectOption: {},
      disableXvfb: false,
      ignoreAllFlags: false
    })
`

### Issue Type

Others

### Operating System

Mac OS

### Do you use Docker?

None

**Comment by RubberArchind** [comment]
what's the error?

**Comment by baba990aini** [comment]
> what's the error? i can run the browser smoothly with that configuration

The log did not report any errors, but after logging into a certain website, when I closed the project and restarted it, I still did not log in and did not save my information. You should try to find a website that can log in to, whichever one works

**Comment by RubberArchind** [comment]
it save my information in my case. I try to login to app.daily.dev, close the browser and rerun the code, open the page again, and i already logged in.

**Comment by baba990aini** [comment]
> it save my information in my case. I try to login to app.daily.dev, close the browser and rerun the code, open the page again, and i already logged in.

emmm，I try it again
