### ISSUE TITLE
reCAPTCHA v3 score very low

### ISSUE THREAD

**Issue by swanilla** [ZFC-Digital/puppeteer-real-browser#230]
### Description

I am running a web app that launches the puppeteer-real-browser instance on demand, i.e. when an API endpoint is hit. The puppeteer should then sign in to a web app that uses CAPTCHAs to protect their sign in page.

I use an extension to solve v2 CAPTCHAs (Capsolver), which does a good job most of the time. But even when it solves it, and I am able to click on the "Log in" button, I get back an error from the web app's API, something like "captcha incorrect"

I suspect it has something to do with the browser's reCAPTCHA v3 score being very low - almost always 0.1 when I check.

What can I do to improve this?

This seems valid for both Docker and local executions.

### Full steps to reproduce the issue

Here is how I launch the browser:

```
    const { browser, page } = await connect(this.getBrowserOptions());

    // Method to retrieve browser launch options
    private getBrowserOptions(): Options {
        const extensionPath = path.join(process.cwd(), 'capsolver', `capsolver_extension_${this.proxyIndex}`);
        if (!fs.existsSync(extensionPath)) {
            throw new Error(`Directory does not exist: ${extensionPath}`);
        }
        if (!fs.existsSync(this.userDataDir)) {
            fs.mkdirSync(this.userDataDir);
        }
        const options: Options = {
            headless: false,
            disableXvfb: false,
            turnstile: true,
            connectOption: {
                defaultViewport: null,
            },
            customConfig: {
                userDataDir: this.userDataDir,
            },
            args: [`--disable-extensions-except=${extensionPath}`, `--load-extension=${extensionPath}`],
        };
        if (this.proxyIndex > 0) {
            const proxyParts = this.proxies[this.proxyIndex - 1].split(':');
            options.proxy = {
                host: proxyParts[0],
                port: parseInt(proxyParts[1]),
                username: proxyParts[2],
                password: proxyParts[3],
            };
        }
        return options;
    }
```

### Issue Type

Performance, Support

### Operating System

Linux, Mac OS

### Do you use Docker?

I don't use Docker

**Comment by rafa-9** [comment]
same issue here

**Comment by ottodriver** [comment]
same, recaptcha seems impossible to bypass at a high rate this days, I've tested a lot of proxies

**Comment by rafa-9** [comment]
@ottodriver @swanilla are you guys using recaptcha solvers?

**Comment by swanilla** [comment]
> @ottodriver @swanilla are you guys using recaptcha solvers?

I use an injected Chrome extension (Capsolver) as part of my browser instance, which seems to operate fine for the v2 reCAPTCHA, but it does not take care of the v3.

**Comment by captainjackrana** [comment]
Same issue here -- the `--user-data-dir` argument used to result in better Recaptcha scores earlier, however lately that's also not helping.

**Comment by RubberArchind** [comment]
have anyone try setting turnstile to false?

**Comment by ottodriver** [comment]
> Any updates ?, I had the same issue using a similar config

Solved with domestic proxies in my case

**Comment by captainjackrana** [comment]
> > Any updates ?, I had the same issue using a similar config
> 
> Solved with domestic proxies in my case

By domestic proxies, do you mean residential proxies within your own country? Which proxy service are you using?

**Comment by mdervisaygan** [comment]
https://github.com/ZFC-Digital/puppeteer-real-browser?tab=readme-ov-file#why-cant-i-pass-recaptcha-v3

**Comment by ottodriver** [comment]
> > > Any updates ?, I had the same issue using a similar config
> > 
> > 
> > Solved with domestic proxies in my case
> 
> By domestic proxies, do you mean residential proxies within your own country? Which proxy service are you using?

Not my own country, the target site country. I'm using DI.

**Comment by rafa-9** [comment]
@mdervisaygan since you closed this topic but there is no solution provided. Can you tell us what needs to be done?

**Comment by mdervisaygan** [comment]
As clearly stated in the readme file, recaptcha v3 checks browser cookies and gives low scores to browsers that have no history with Google. 
This is also clearly discussed in the stackoverflow link in the readme file. You can log in to a Google account and use it.


I can't offer a solution for every issue. I cannot add a built-in Google login module. Some topics need to be searched by people who dislike my comments, hate research and expect everything ready. I clearly added the cause and solution to this problem in the readme file, that's all I can do. I try to spend time on open source projects in my limited time, but when I do, I still get dislikes and requests for solutions even though I have posted the problem and the solution. Please read the link I provided. Everything about the problem is written there. 


I hope this long and repetitive explanation answers your questions.

Translated with DeepL.com (free version)
