### ISSUE TITLE
brotector test fails

### ISSUE THREAD

**Issue by xzymxeqgmc** [ZFC-Digital/puppeteer-real-browser#231]
### Description

brotector test fails

### Full steps to reproduce the issue

run esm tests

<img width="1197" alt="Screenshot 2024-11-30 at 21 12 31" src="https://github.com/user-attachments/assets/d8662ef1-6e9b-4aae-9e0b-99ecb91864af">

### Issue Type

Bug

### Operating System

Linux

### Do you use Docker?

I don't use Docker

**Comment by mdervisaygan** [comment]
It should be resolved, please try again. You should not play with args and fingerprint values to avoid getting caught

**Comment by xzymxeqgmc** [comment]
> It should be resolved, please try again. You should not play with args and fingerprint values to avoid getting caught

I literally just cloned this repo and ran the tests, nothing else
