### ISSUE TITLE
migration  puppeteer  to puppeteer-real-browse

### ISSUE THREAD

**Issue by williamfjm** [ZFC-Digital/puppeteer-real-browser#232]
### Description

I have had the need to migrate to puppeteer-real-browse (thanks for this great work). But I have had a problem migrating my code from puppeteer, with the options headless: false, and executablePath: they are invisible for this library for the path found in it. export option CHROME_PATH= ... but the application always launches invisible in headless mode no matter what option I configure in the code, this happens in Linux when it is launched From the console in Windows it works. 

### Full steps to reproduce the issue

const { connect } = require('puppeteer-real-browser');

console.log("hello");
connect({
    headless: false,
    executablePath: '/usr/bin/google-chrome-stable_old',   
     args: [
             '--no-sandbox',
               // '--disable-setuid-sandbox',
              '--headful',
  
        ],       
     turnstile: true,
     
})
.then(async response => {
    console.log("loud....");
    const { browser, page } = response;
    await page.goto('https://books.toscrape.com/');
    await page.screenshot({ path: 'books.png' });
    await browser.close();
})
.catch(error => {
    console.log(error.message);
});
-------------------------------------------------

export DISPLAY=:0

----------------------------------

node test.js

_______________________________

sussess execution but not visible browser

### Issue Type

Support

### Operating System

Linux

### Do you use Docker?

None

**Comment by RubberArchind** [comment]
it should be inside custom config, try to set it like this
```
connect({
headless: false,
customConfig: {
    chromePath: '/usr/bin/google-chrome-stable_old'
},
args: [
'--no-sandbox',
    ],       
 turnstile: true,
})
```

**Comment by RubberArchind** [comment]
tes it is,  it already described in the README

https://github.com/ZFC-Digital/puppeteer-real-browser?tab=readme-ov-file#installation

`If you are using a Linux operating system, xvfb must be installed for the library to work correctly.`

**Comment by williamfjm** [comment]
This library uses xvfb in Linux, use those commands to access the virtual desktop 
ps aux | grep Xvfb //list virtual desktops
x11vnc -storepasswd //set optional password
 x11vnc -display :99 -localhost -rfbport 4006 //configuration for connection via ssh tunnel for security
and I connect through a tightVNC type client 
but I have two doubts about it 
1. Can I configure the resolution of those desktops to save memory?
2. How can I make sure that the virtual desktop dies when the application dies? Sometimes it ends due to exceptions. And the desktops are left taking up memory, of which I don't have much.

**Comment by RubberArchind** [comment]
1. I never try it but I think you can do that

2. put your code in try, catch, finally

`try{
//your code here
} catch(e){
//handle exception here
}{
//do check here, and do browser.close() if the browser still open
}`

**Comment by mdervisaygan** [comment]
please try:
`disableXvfb: true`
https://github.com/ZFC-Digital/puppeteer-real-browser?tab=readme-ov-file#usage
