### ISSUE TITLE
Not work windows 8.1 about:blank

### ISSUE THREAD

**Issue by lutskboy** [ZFC-Digital/puppeteer-real-browser#237]
### Description

I have this code
`      

      console.log('before');
      const { page } = await connect({
        headless: false,
        fingerprint: true,
        turnstile: true,
        tf: true,
      });
     
    console.log('after');

    await page.goto('https://bypass.go/');

`

I see before in the console but I can't see the after. my browser open about:blank and do not go to page https://bypass.go/

### Full steps to reproduce the issue

can fix it?

### Do you use Docker?

None

**Comment by boiwantlearncode** [comment]
Similar issue. Two windows are opened, one is about:blank, the other the website I want to goto. Puppeteer can't access the content on the intended website.

**Comment by mdervisaygan** [comment]
I get an error that the related site does not exist, so it is not a library problem but a domain problem.

**Comment by lutskboy** [comment]
It has nothing to do with the domain. I wrote any domain as an example.

**Comment by RubberArchind** [comment]
how if you make a new page and do goto with new page, is it still the same?

**Comment by lutskboy** [comment]
the script logic stops at this point

`  const { page } = await connect({
    headless: false,
    fingerprint: true,
    turnstile: true,
    tf: true,
  });`
