### ISSUE TITLE
TypeError: browser.createIncognitoBrowserContext is not a function

### ISSUE THREAD

**Issue by Yusufkulcu** [ZFC-Digital/puppeteer-real-browser#243]
### Description

I want to allocate cookies for each tab using the "createIncognitoBrowserContext" function, but it gives an error. What is the problem or how can I keep cookies separate for each tab

### Full steps to reproduce the issue

I want to allocate cookies for each tab using the "createIncognitoBrowserContext" function, but it gives an error. What is the problem or how can I keep cookies separate for each tab

![image](https://github.com/user-attachments/assets/b459f99f-4159-4129-8610-de4b7b8b1a89)

### Issue Type

Others

### Operating System

Windows 10

### Do you use Docker?

None

**Comment by mdervisaygan** [comment]
Try this also with a normal puppeteer. This feature is not supported by puppeteer as explained in the error.

**Comment by firolimarazaqaqu32440-netizen** [comment]
> Try this also with a normal puppeteer. This feature is not supported by puppeteer as explained in the error.

I actually tried it and it works flawlessly
