### ISSUE TITLE
Not working on Raspberry PI

### ISSUE THREAD

**Issue by matigarowel** [ZFC-Digital/puppeteer-real-browser#249]
### Description

I tried to run it in raspberry PI raspbian OS and cannot solve turnstile

### Full steps to reproduce the issue

using below code 

const { page, browser } = await connect({ headless: false, turnstile: true, })
let token: string | null = null
let startDate = Date.now()
while (!token && (Date.now() - startDate) < 10000) {
  token = await page.evaluate(() => {
      try {
          let item = (document.querySelector('[name="cf-turnstile-response"]') as HTMLInputElement).value
          console.log("item", item)
          return item && item.length > 20 ? item : null
      } catch (e: any) {
          return e.message
      }
  })

  await new Promise(r => setTimeout(r, 1000));
}

### Issue Type

Support

### Operating System

Linux

### Do you use Docker?

None

**Comment by matigarowel** [comment]
Closing this it is already running

**Comment by RubberArchind** [comment]
how you solve this?

**Comment by matigarowel** [comment]
> how you solve this?

I deploy this [https://github.com/ZFC-Digital/cf-clearance-scraper](https://github.com/ZFC-Digital/cf-clearance-scraper) on Raspberry PI docker. the turnstile-min mode work fast.
